### ISSUE TITLE
Seitenfehler bei automatischem Versumbruch

### ISSUE THREAD

**Issue by Little-Ben** [tim4724/u-song-Stage-Monitor-for-Songbeamer#1]
Habe in den OPTIONEN auf Registerkarte SONG im Bereich TEXT bei MAXIMALE ZEILENZAHL einen Wert (zb 4) eingetragen. Dies bewirkt, dass eine längerer Vers automatisch nach der zb 4. Zeile umgebrochen wird.

Dieser Umbruch/Seitenwechsel wird nicht korrekt in usong interpretiert.

Beispiellied:

Vers1
Vers1Zeile1
Vers1Zeile2
Vers1Zeile3
Vers1Zeile4
Vers1Zeile5
Vers1Zeile6
Vers 2
Vers2Zeile1
Vers2Zeile2
Vers2Zeile3
Vers2Zeile4
Vers2Zeile5
Vers2Zeile6

Heißt aus Vers 1 mit zb 6 Zeilen werden im Songbeamer 2 Folien  (sagen wir: Vers1a und Vers1b). Auf die 2. Teilfolie (also Vers1b) wechsel ich in Songbeamer regulär zb mit Mausklick oder Pfeiltasten (sieht dort auch aus wie eine weitere Folie).

Dieser Mausklick bewirkt jedoch in usong bereits den Wechsel auf die nächste reguläre Liedfolie (also Vers2a).

(getestet mit Songbeamer 5.00 und usong release 2.0.3)

**Comment by tim4724** [comment]
Das Feature in Songbeamer kannte ich ja gar nicht :)
Ich schaue dass ich eine Lösung finde.

**Comment by tim4724** [comment]
In Version 2.0.5 kann man als schnelle Lösung folgenden Registry Eintrag setzen:
Die Anzahl an maximalen Zeilen pro Folie lassen sich setzen. Der Wert 0 bedeutet, dass Feature wird nicht genutzt.

`HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\tim\usong\core\songparser` **max_lines_per_page** _{0,1,2,3...}_

Beispiel: Maximal 3 Zeilen in einer Folie:
`reg add "HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\tim\usong\core\songparser" /v max_lines_per_page /t REG_SZ /d 3 /f`

Feature deaktivieren:
`reg add "HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\tim\usong\core\songparser" /v max_lines_per_page /t REG_SZ /d 0 /f`

**Comment by tim4724** [comment]
Am besten wäre es natürlich, wenn man die aktuelle Einstellung aus Songbeamer auslesen könnte.
Mindestens sollte es aber noch eine Möglichkeit geben, diese Einstellungen über ein Menü zu wählen.

**Comment by Little-Ben** [comment]
Beim Vers greifts schonmal :-) beim Refrain leider noch nicht. (getestet mit Lied "Jesus komm" aus den Default-Liedern bei Neuinstallation von Songbeamer mit max 4 Zeilen pro Folie)

**Comment by tim4724** [comment]
Stimmt danke für den Hinweis :)
Habe den Fehler korrigiert in Version 2.0.6

**Comment by Little-Ben** [comment]
Jap, geht. auch hierfür vielen dank!

**Comment by tim4724** [comment]
In Version 2.0.7 wird die Einstellung "Maximale Zeilenanzahl pro Folie" automatisch aus der SongBeamer-Installation ausgelesen. (Getestet mit SongBeamer Version 5.0)
Sollte dies aus irgendeinem Grund mit einer bestimmten SongBeamer Version nicht mehr klappen, kann man die Einstellung manuell im neuen Einstellungsmenü setzen.
