### ISSUE TITLE
IndexOutOfBoundsException beim erneuten Start

### ISSUE THREAD

**Issue by Little-Ben** [tim4724/u-song-Stage-Monitor-for-Songbeamer#2]
Wenn ich usong bereits einmal geschlossen habe (über Tray, Beenden) und dann wieder öffnen will kommt es _meistens_ zu einem Fehler beim erneuten Starten von usong.

Fataler Fehler!
Die Anwendung wird beendet
java.lang.IndexOutOfBoundsException: Invalid index

Scheint mit der Registry zusammenzuhängen.
Lösche ich manuell den Registry-Key 
[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\tim\usong\core\ui\preview]

und starte dann usong, 
dann geht es wieder.

getestet mit Songbeamer 5.00
usong release 2.0.3
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Windows 10 Home 1803

**Comment by Little-Ben** [comment]
manchmal muss man auch noch 
[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\tim\usong\core\ui] 
löschen.

Da ist aber auch der gemerkte Lied-Pfad weg und man muss ihn dann halt neu einstellen.

**Comment by tim4724** [comment]
Kannst du bitte bei Gelegenheit prüfen, ob der Fehler mit Version **2.0.4** immernoch auftritt? 
Ich kann den Fehler aktuell bei mir nicht wirklich reproduzieren. 

Im Verzeichnis `%Appdata%/uSongServer/log` solltest du auch den kompletten Stacktrace in einer Log Datei finden. 
Kannst du mir den schicken, falls das Problem mit der neuen Version auch auftritt?
Danke :)

**Comment by Little-Ben** [comment]
Cool, danke. Ich schau mal mit der neuen Version bzw Stacktrace, wird aber vermutlich heute nichts mehr.

**Comment by Little-Ben** [comment]
ok, Problem scheint mit 2.0.4 behoben zu sein! Zumindest konnte ich es gut 10x hintereinander öffnen/schließen.
