### ISSUE TITLE
falsche Folienzuordnung bei "Titel auf eigener Seite"

### ISSUE THREAD

**Issue by Little-Ben** [tim4724/u-song-Stage-Monitor-for-Songbeamer#3]
Ähnlich zu dem beschriebenen Fall in #1 kommt es zu einer falschen Folienzuordnung in usong, wenn man den Titel als eigene Folie anzeigt (Songbeamer / Optionen / Song / Titel / Auf extra Seite)

Songbeamer 5.00
usong 2.0.4
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Windows 10 Home 1803

**Comment by tim4724** [comment]
In Version 2.0.5 kann man als schnelle Lösung folgenden Registry Eintrag setzen:

`HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\tim\usong\core\songparser` **title_has_own_page** _true/false_

Oder einfach zum aktivieren ausführen:
`reg add "HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\tim\usong\core\songparser /v title_has_own_page /t REG_SZ /d true /f`

Titel auf eigener Folie zeigen deaktivieren:
`reg add "HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\tim\usong\core\songparser /v title_has_own_page /t REG_SZ /d false /f`

**Comment by tim4724** [comment]
Am besten wäre es natürlich, wenn man die aktuelle Einstellung aus Songbeamer auslesen könnte.
Mindestens sollte es aber noch eine Möglichkeit geben, diese Einstellungen über ein Menü zu wählen.

**Comment by Little-Ben** [comment]
super geht, danke!

**Comment by tim4724** [comment]
In Version 2.0.7 wird die Einstellung "Titel auf eigener Seite" automatisch aus der SongBeamer-Installation ausgelesen. (Getestet mit SongBeamer Version 5.0)
Sollte dies aus irgendeinem Grund mit einer bestimmten SongBeamer Version nicht mehr klappen, kann man die Einstellung manuell im neuen Einstellungsmenü setzen.
